# Generated by Django 5.2.17 on 2026-09-21 08:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('gstin', models.CharField(blank=True, max_length=25, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=20, verbose_name='PAN Number')),
                ('business_type', models.CharField(choices=[('manufacturer', 'Food Manufacturer / FMCG'), ('processor', 'Flour Mill / Spice Processor / Dal Mill'), ('distributor', 'Wholesaler / Distributor'), ('retail_chain', 'Supermarket / Retail Chain'), ('exporter', 'Export / Trading House'), ('horeca', 'Hotel / Restaurant / Catering (HoReCa)'), ('other', 'Other Business Enterprise')], default='manufacturer', max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False, help_text='Checked after GST verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2B Company Profile',
                'verbose_name_plural': 'B2B Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('quote_confirmed', 'Quote Confirmed / Proforma Issued'), ('processing', 'In Processing / Packaging'), ('dispatched', 'Dispatched / In Transit'), ('delivered', 'Delivered & Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid / Pending'), ('advance_paid', 'Advance Token Paid'), ('fully_paid', 'Fully Settled')], default='unpaid', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% GST', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, help_text='e.g. VRL Logistics, Safechem Express', max_length=120)),
                ('tracking_consignment_no', models.CharField(blank=True, help_text='LR / Consignment Note No.', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, help_text='e.g. KA-01-AB-1234', max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.quoterequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2B Commercial Order',
                'verbose_name_plural': 'B2B Commercial Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in metric units', max_digits=10)),
                ('unit', models.CharField(default='Metric Tons', max_length=30)),
                ('packaging', models.CharField(default='50kg PP Bags with Liner', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per Metric Ton / Unit in INR', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
            },
        ),
    ]
