# Generated by Django 5.2.17 on 2026-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_order_additional_requirements_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_upi_id', models.CharField(default='9902155348@axl', help_text='Official Business UPI ID (e.g. 9902155348@axl)', max_length=100)),
                ('payee_name', models.CharField(default='Balaji Ingredients', help_text='Payee business display name for UPI payments', max_length=150)),
                ('qr_image', models.ImageField(blank=True, help_text='Upload custom Business UPI QR Code image', null=True, upload_to='payment_qr/')),
                ('qr_image_url', models.CharField(default='images/upi_qr.jpg', help_text='Static / fallback image path for QR Code', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set as active configuration for customer checkout')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business UPI Payment Setting',
                'verbose_name_plural': 'Business UPI Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI Payment')], default='cod', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_utr_number',
            field=models.CharField(blank=True, help_text='Transaction reference number from customer UPI app', max_length=100, verbose_name='UPI Transaction / UTR Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cod', 'COD'), ('verification_pending', 'Verification Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='cod', max_length=30),
        ),
    ]
