# Generated by Django 5.2.17 on 2026-09-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='◈', max_length=20)),
                ('accent_color', models.CharField(default='#2e7031', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('grade', models.CharField(default='Sortex Cleaned Grade A', max_length=100)),
                ('purity_percentage', models.CharField(default='99.5% Min', max_length=50)),
                ('moisture_content', models.CharField(default='< 11%', max_length=50)),
                ('shelf_life', models.CharField(default='12 Months', max_length=80)),
                ('origin', models.CharField(default='India', max_length=100)),
                ('min_order_qty', models.CharField(default='1 Metric Ton (1000 kg)', max_length=100)),
                ('packaging_options', models.CharField(default='25kg / 50kg PP Bags with LDPE liner, 1000kg FIBC Jumbo Bags', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_gradient', models.CharField(default='linear-gradient(135deg, #c8a96e 0%, #a07840 50%, #7a5c2c 100%)', help_text='CSS gradient fallback when image is not uploaded', max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='e.g. Protein Content, Foreign Matter', max_length=120)),
                ('parameter_value', models.CharField(help_text='e.g. 22.0% Min, < 0.15%', max_length=150)),
                ('test_method', models.CharField(blank=True, help_text='e.g. AOAC / IS:4333', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Technical Specification',
                'verbose_name_plural': 'Technical Specifications',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('gstin', models.CharField(blank=True, max_length=30, verbose_name='GSTIN / Tax ID')),
                ('quantity_volume', models.CharField(help_text='e.g. 5 MT, 20 MT (1 Full Truckload), 100 Bags', max_length=100)),
                ('packaging_preference', models.CharField(default='50kg PP Bags with Liner', help_text='e.g. 25kg PP, 50kg PP, 1 MT Jumbo Tote Bag, Bulk', max_length=120)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_pincode', models.CharField(blank=True, max_length=20)),
                ('delivery_timeline', models.CharField(blank=True, help_text='e.g. Within 7 days, Monthly contract', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Specific grade requirements, target price, etc.')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('quote_sent', 'Quote Sent'), ('converted', 'Converted to Order'), ('closed', 'Closed')], default='new', max_length=25)),
                ('quoted_price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Official price per MT or Kg quoted to client', max_digits=12, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='products.product')),
            ],
            options={
                'verbose_name': 'Quote Request (RFQ)',
                'verbose_name_plural': 'Quote Requests (RFQs)',
                'ordering': ['-created_at'],
            },
        ),
    ]
