# Generated by Django 5.2.17 on 2026-09-22 04:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_name',
            field=models.CharField(default='Quintal (100 kg)', help_text='Unit of measurement e.g. Quintal, Metric Ton, 50kg Bag', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('8500.00'), help_text='Price per unit in INR (₹)', max_digits=12),
        ),
    ]
