# Generated by Django 5.2.17 on 2026-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_unit_name_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.CharField(blank=True, default='Food Manufacturing, Snacks, Bakery, Commercial Milling', help_text='Key commercial use cases', max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quotation Sent'), ('negotiation', 'Negotiation'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='new', max_length=25),
        ),
    ]
