# Generated by Django 5.2.17 on 2026-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Balaji Ingredients', max_length=150)),
                ('tagline', models.CharField(default="Let's craft what's next, together.", max_length=250)),
                ('hero_headline', models.CharField(default="Let's craft what's next, together.", max_length=250)),
                ('hero_subtitle', models.TextField(default='Premium food ingredients, carefully sourced, processed and delivered with consistency you can trust.')),
                ('about_title', models.CharField(default='Precision Food Ingredients for Value-Added Formulations', max_length=250)),
                ('about_text', models.TextField(default='From traditional grains and pulses to carefully processed spice ingredients, Balaji Ingredients works with trusted sourcing networks and controlled processing practices to provide consistent ingredients for commercial applications.')),
                ('phone', models.CharField(default='+91 98450 11223', max_length=50)),
                ('email', models.EmailField(default='yadavdarshanms@gmail.com', max_length=254)),
                ('office_address', models.TextField(default='APMC Yard & Industrial Processing Facility, Kalaburagi / Bengaluru, Karnataka, India')),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM – 7:00 PM IST', max_length=120)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='sitestat',
            name='description',
            field=models.CharField(blank=True, help_text='Supporting label or detail', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitestat',
            name='label',
            field=models.CharField(help_text='e.g. Years / Product Experience', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitestat',
            name='value',
            field=models.CharField(help_text='e.g. 25+ or 500+', max_length=30),
        ),
    ]
